import { join } from "path";

type RNG = () => number;

function makeRng(seed: number): RNG {
  let state = seed >>> 0;
  return () => {
    state = (1664525 * state + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

const rng = makeRng(20260210);

function randInt(min: number, max: number): number {
  return Math.floor(rng() * (max - min + 1)) + min;
}

function pick<T>(items: readonly T[]): T {
  return items[randInt(0, items.length - 1)];
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function isoDateFromOffset(daysOffset: number): string {
  const base = new Date("2020-01-01T00:00:00.000Z");
  base.setUTCDate(base.getUTCDate() + daysOffset);
  return base.toISOString().slice(0, 10);
}

const firstNames = [
  "Alex", "Jordan", "Taylor", "Morgan", "Casey", "Avery", "Riley", "Cameron",
  "Parker", "Hayden", "Reese", "Quinn", "Rowan", "Skyler", "Dakota", "Kai",
  "Elliot", "Sam", "Jules", "Remy", "Blake", "Drew", "Logan", "Toby"
] as const;

const lastNames = [
  "Smith", "Johnson", "Williams", "Brown", "Jones", "Miller", "Davis", "Garcia",
  "Rodriguez", "Wilson", "Martinez", "Anderson", "Thomas", "Taylor", "Moore",
  "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Clark", "Lewis"
] as const;

const industries = [
  "Healthcare", "Finance", "Retail", "Manufacturing", "Technology", "Energy",
  "Telecom", "Education", "Transportation", "Hospitality"
] as const;

const jobTitles = [
  "Consultant", "Senior Consultant", "Principal Consultant", "Business Analyst",
  "Data Analyst", "Project Manager", "Solution Architect", "Developer",
  "QA Engineer", "Engagement Manager"
] as const;

const projectStatuses = ["planned", "active", "on_hold", "completed", "cancelled"] as const;
const invoiceStatuses = ["draft", "sent", "paid", "overdue", "void"] as const;
const projectRoles = [
  "Project Lead", "Developer", "Analyst", "QA", "Architect", "Consultant"
] as const;

const departmentCount = 100;
const employeeCount = 220;
const clientCount = 120;
const projectCount = 180;
const timesheetCount = 1400;
const invoiceCount = 220;

const lines: string[] = [];

lines.push("-- Auto-generated SQL script");
lines.push("-- Generated by: generate-sql-mysql.ts");
lines.push("");
lines.push("START TRANSACTION;");
lines.push("");
lines.push("SET FOREIGN_KEY_CHECKS = 0;");
lines.push("");

lines.push("DROP TABLE IF EXISTS Timesheet;");
lines.push("DROP TABLE IF EXISTS Employee_Project;");
lines.push("DROP TABLE IF EXISTS Invoice;");
lines.push("DROP TABLE IF EXISTS Project;");
lines.push("DROP TABLE IF EXISTS Employee;");
lines.push("DROP TABLE IF EXISTS Client;");
lines.push("DROP TABLE IF EXISTS Department;");
lines.push("");
lines.push("SET FOREIGN_KEY_CHECKS = 1;");
lines.push("");

lines.push("CREATE TABLE Department (");
lines.push("  department_id INT PRIMARY KEY,");
lines.push("  name VARCHAR(100) NOT NULL,");
lines.push("  manager_employee_id INT NULL");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("CREATE TABLE Employee (");
lines.push("  employee_id INT PRIMARY KEY,");
lines.push("  first_name VARCHAR(50) NOT NULL,");
lines.push("  last_name VARCHAR(50) NOT NULL,");
lines.push("  email VARCHAR(150) NOT NULL UNIQUE,");
lines.push("  hire_date DATE NOT NULL,");
lines.push("  job_title VARCHAR(100) NOT NULL,");
lines.push("  salary DECIMAL(12,2) NOT NULL,");
lines.push("  department_id INT NOT NULL,");
lines.push("  CONSTRAINT fk_employee_department");
lines.push("    FOREIGN KEY (department_id) REFERENCES Department(department_id)");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("ALTER TABLE Department");
lines.push("  ADD CONSTRAINT fk_department_manager");
lines.push("  FOREIGN KEY (manager_employee_id)");
lines.push("  REFERENCES Employee(employee_id);");
lines.push("");

lines.push("CREATE TABLE Client (");
lines.push("  client_id INT PRIMARY KEY,");
lines.push("  name VARCHAR(150) NOT NULL,");
lines.push("  industry VARCHAR(100) NOT NULL,");
lines.push("  contact_name VARCHAR(100) NOT NULL,");
lines.push("  contact_email VARCHAR(150) NOT NULL,");
lines.push("  contact_phone VARCHAR(30) NOT NULL");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("CREATE TABLE Project (");
lines.push("  project_id INT PRIMARY KEY,");
lines.push("  client_id INT NOT NULL,");
lines.push("  name VARCHAR(150) NOT NULL,");
lines.push("  description TEXT NOT NULL,");
lines.push("  start_date DATE NOT NULL,");
lines.push("  end_date DATE NULL,");
lines.push("  status VARCHAR(30) NOT NULL,");
lines.push("  budget DECIMAL(12,2) NOT NULL,");
lines.push("  CONSTRAINT fk_project_client");
lines.push("    FOREIGN KEY (client_id) REFERENCES Client(client_id)");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("CREATE TABLE Employee_Project (");
lines.push("  employee_id INT NOT NULL,");
lines.push("  project_id INT NOT NULL,");
lines.push("  assignment_start_date DATE NOT NULL,");
lines.push("  role_on_project VARCHAR(100) NOT NULL,");
lines.push("  allocation_percent DECIMAL(5,2) NOT NULL,");
lines.push("  assignment_end_date DATE NULL,");
lines.push("  PRIMARY KEY (employee_id, project_id, assignment_start_date),");
lines.push("  CONSTRAINT fk_employee_project_employee");
lines.push("    FOREIGN KEY (employee_id) REFERENCES Employee(employee_id),");
lines.push("  CONSTRAINT fk_employee_project_project");
lines.push("    FOREIGN KEY (project_id) REFERENCES Project(project_id)");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("CREATE TABLE Timesheet (");
lines.push("  timesheet_id INT PRIMARY KEY,");
lines.push("  employee_id INT NOT NULL,");
lines.push("  project_id INT NOT NULL,");
lines.push("  work_date DATE NOT NULL,");
lines.push("  hours DECIMAL(4,2) NOT NULL,");
lines.push("  billable_flag TINYINT(1) NOT NULL,");
lines.push("  notes TEXT NULL,");
lines.push("  CONSTRAINT fk_timesheet_employee");
lines.push("    FOREIGN KEY (employee_id) REFERENCES Employee(employee_id),");
lines.push("  CONSTRAINT fk_timesheet_project");
lines.push("    FOREIGN KEY (project_id) REFERENCES Project(project_id)");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("CREATE TABLE Invoice (");
lines.push("  invoice_id INT PRIMARY KEY,");
lines.push("  project_id INT NOT NULL,");
lines.push("  invoice_date DATE NOT NULL,");
lines.push("  amount DECIMAL(12,2) NOT NULL,");
lines.push("  status VARCHAR(30) NOT NULL,");
lines.push("  notes TEXT NULL,");
lines.push("  CONSTRAINT fk_invoice_project");
lines.push("    FOREIGN KEY (project_id) REFERENCES Project(project_id)");
lines.push(") ENGINE=InnoDB;");
lines.push("");

lines.push("-- Seed Department (100 rows)");
for (let i = 1; i <= departmentCount; i += 1) {
  lines.push(
    `INSERT INTO Department (department_id, name, manager_employee_id) VALUES (${i}, ${sqlString(`Department ${String(i).padStart(3, "0")}`)}, NULL);`
  );
}
lines.push("");

lines.push("-- Seed Employee (220 rows)");
const employeeDepartments: number[] = [];
for (let i = 1; i <= employeeCount; i += 1) {
  const first = pick(firstNames);
  const last = pick(lastNames);
  const depId = randInt(1, departmentCount);
  employeeDepartments.push(depId);
  const hireDate = isoDateFromOffset(randInt(0, 2100));
  const salary = (62_000 + randInt(0, 95_000)).toFixed(2);
  const email = `${first.toLowerCase()}.${last.toLowerCase()}${i}@consultco.example`;
  lines.push(
    `INSERT INTO Employee (employee_id, first_name, last_name, email, hire_date, job_title, salary, department_id) VALUES (${i}, ${sqlString(first)}, ${sqlString(last)}, ${sqlString(email)}, ${sqlString(hireDate)}, ${sqlString(pick(jobTitles))}, ${salary}, ${depId});`
  );
}
lines.push("");

lines.push("-- Assign one manager per department where possible");
for (let dep = 1; dep <= departmentCount; dep += 1) {
  let managerId = -1;
  for (let e = 1; e <= employeeCount; e += 1) {
    if (employeeDepartments[e - 1] === dep) {
      managerId = e;
      break;
    }
  }
  if (managerId > 0) {
    lines.push(`UPDATE Department SET manager_employee_id = ${managerId} WHERE department_id = ${dep};`);
  }
}
lines.push("");

lines.push("-- Seed Client (120 rows)");
for (let i = 1; i <= clientCount; i += 1) {
  const companyName = `Client ${String(i).padStart(3, "0")} LLC`;
  const contactFirst = pick(firstNames);
  const contactLast = pick(lastNames);
  const contact = `${contactFirst} ${contactLast}`;
  const email = `${contactFirst.toLowerCase()}.${contactLast.toLowerCase()}${i}@clientco.example`;
  const phone = `+1-555-${String(randInt(100, 999))}-${String(randInt(1000, 9999))}`;
  lines.push(
    `INSERT INTO Client (client_id, name, industry, contact_name, contact_email, contact_phone) VALUES (${i}, ${sqlString(companyName)}, ${sqlString(pick(industries))}, ${sqlString(contact)}, ${sqlString(email)}, ${sqlString(phone)});`
  );
}
lines.push("");

lines.push("-- Seed Project (180 rows)");
const projectDateOffsets: number[] = [];
for (let i = 1; i <= projectCount; i += 1) {
  const startOffset = randInt(100, 2300);
  projectDateOffsets.push(startOffset);
  const maybeEnded = rng() > 0.3;
  const endDate = maybeEnded ? isoDateFromOffset(startOffset + randInt(30, 360)) : null;
  const status = maybeEnded ? pick(projectStatuses) : "active";
  const budget = (120_000 + randInt(0, 2_100_000)).toFixed(2);
  lines.push(
    `INSERT INTO Project (project_id, client_id, name, description, start_date, end_date, status, budget) VALUES (${i}, ${randInt(1, clientCount)}, ${sqlString(`Project ${String(i).padStart(3, "0")}`)}, ${sqlString(`Consulting engagement for client ${String(randInt(1, clientCount)).padStart(3, "0")}`)}, ${sqlString(isoDateFromOffset(startOffset))}, ${endDate ? sqlString(endDate) : "NULL"}, ${sqlString(status)}, ${budget});`
  );
}
lines.push("");

lines.push("-- Seed Employee_Project mapping");
const assignmentSet = new Set<string>();
for (let projectId = 1; projectId <= projectCount; projectId += 1) {
  const assignmentCount = randInt(3, 8);
  for (let j = 0; j < assignmentCount; j += 1) {
    let employeeId = randInt(1, employeeCount);
    let key = `${employeeId}-${projectId}`;
    let guard = 0;
    while (assignmentSet.has(key) && guard < 10) {
      employeeId = randInt(1, employeeCount);
      key = `${employeeId}-${projectId}`;
      guard += 1;
    }
    if (assignmentSet.has(key)) {
      continue;
    }
    assignmentSet.add(key);
    const startOffset = projectDateOffsets[projectId - 1] + randInt(0, 60);
    const endOffset = rng() > 0.5 ? startOffset + randInt(45, 240) : -1;
    lines.push(
      `INSERT INTO Employee_Project (employee_id, project_id, assignment_start_date, role_on_project, allocation_percent, assignment_end_date) VALUES (${employeeId}, ${projectId}, ${sqlString(isoDateFromOffset(startOffset))}, ${sqlString(pick(projectRoles))}, ${randInt(20, 100).toFixed(2)}, ${endOffset > 0 ? sqlString(isoDateFromOffset(endOffset)) : "NULL"});`
    );
  }
}
lines.push("");

lines.push("-- Seed Timesheet (1400 rows)");
for (let i = 1; i <= timesheetCount; i += 1) {
  const projectId = randInt(1, projectCount);
  const workOffset = projectDateOffsets[projectId - 1] + randInt(0, 365);
  const hours = (randInt(1, 8) + (rng() > 0.7 ? 0.5 : 0)).toFixed(2);
  const billable = rng() > 0.12 ? "1" : "0";
  lines.push(
    `INSERT INTO Timesheet (timesheet_id, employee_id, project_id, work_date, hours, billable_flag, notes) VALUES (${i}, ${randInt(1, employeeCount)}, ${projectId}, ${sqlString(isoDateFromOffset(workOffset))}, ${hours}, ${billable}, ${sqlString(`Work log entry ${i}`)});`
  );
}
lines.push("");

lines.push("-- Seed Invoice (220 rows)");
for (let i = 1; i <= invoiceCount; i += 1) {
  const projectId = randInt(1, projectCount);
  const invoiceOffset = projectDateOffsets[projectId - 1] + randInt(30, 540);
  const amount = (8_000 + randInt(0, 190_000)).toFixed(2);
  const note = rng() > 0.2 ? `Invoice note ${i}` : "Adjustment pending review";
  lines.push(
    `INSERT INTO Invoice (invoice_id, project_id, invoice_date, amount, status, notes) VALUES (${i}, ${projectId}, ${sqlString(isoDateFromOffset(invoiceOffset))}, ${amount}, ${sqlString(pick(invoiceStatuses))}, ${sqlString(note)});`
  );
}
lines.push("");

lines.push("COMMIT;");
lines.push("");

const outputPath = join(import.meta.dir, "init-seed-mysql.sql");
await Bun.write(outputPath, `${lines.join("\n")}\n`);
console.log(`SQL script written to: ${outputPath}`);
